Charset: "UTF-8"
Other:
  #  BasePath: "/home/simon/code/golang/src/github.com/blog"
  views:
    extension: "html"
    path: ""
  server:
    addr: ":28183"
  databases:
    default: "mysql"
    mysql:
      addr: "root:root@(192.168.1.107)/blog?charset=utf8mb4&parseTime=True&loc=Local"